server:
  tomcat:
    uri-encoding: UTF-8
  port: 8001
spring:
  profiles:
    active: dev
  application:
    name: node12-server-8001
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true